application: colleensnr
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: django
  version: "1.4"

builtins:
- django_wsgi: on

includes:
  - dsite/

handlers:
- url: /static
  static_dir: static

- url: /admin
  login: admin
  script: google.appengine.ext.django.main.app

skip_files:
  - ^(.*/)?app\.yaml
  - ^(.*/)?app\.yml
  - ^(.*/)?index\.yaml
  - ^(.*/)?index\.yml
  - ^(.*/)?#.*#
  - ^(.*/)?.*~
  - ^(.*/)?.*\.py[co]
  - ^(.*/)?.*/RCS/.*
  - ^(.*/)?\..*
  - ^(.*/)?closure
  - ^(.*/)?django
  - ^(.*/)?google_appengine
