application: colleensnr
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: django
  version: "1.5"

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'

handlers:
- url: /static
  static_dir: static

- url: /admin
  login: admin
  script: google.appengine.ext.django.main.app

- url: /css
  static_dir: app/css

- url: /img
  static_dir: app/img

- url: /js
  static_dir: app/js

- url: /lib
  static_dir: app/lib

- url: /partials
  static_dir: app/partials

- url: /
  static_files: app/index.html
  upload: app/index.html

- url: /.*
  script: main.app
