application: colleensnr
version: 1
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: django
  version: "1.5"

env_variables:
  DJANGO_SETTINGS_MODULE: 'settings'

handlers:
- url: /static
  static_dir: static

- url: /admin
  login: admin
  script: google.appengine.ext.django.main.app

- url: /(img|css|js|partials|lib)(.*)
  static_files: app/\1/\2
  upload: app/.*

- url: /
  static_files: app/index.html
  upload: app/index.html

- url: /.*
  script: main.app
